name: CMake

on:
  pull_request:
  push:
    branches:
      - main
      - master

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

# Use a bash shell so we can use the same syntax for environment variable
# access regardless of the host operating system
defaults:
  run:
    shell: bash

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        include:
        - os: ubuntu-latest
          ENABLE_COVERAGE: ON
        - os: windows-latest
          # Windows works differently
          ENABLE_COVERAGE: OFF
        - os: macos-latest
          ENABLE_COVERAGE: ON


    steps:
    - uses: actions/checkout@v2

    - name: Install pip dependencies
      if: runner.os != 'MacOS'
      run: |
        pip3 install wheel setuptools

    - name: Install pip dependencies
      if: runner.os == 'MacOS'
      run: |
        pip3 install --use-pep517 wheel setuptools

#    - name: Setup upterm session
#      uses: lhotari/action-upterm@v1

    - name: Install / Configure dependencies
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          echo "Using chocolatey to install OpenCppCoverage"
          choco install opencppcoverage
          # Add to Path
          echo "C:/Program Files/OpenCppCoverage" >> $GITHUB_PATH
        fi;

    - name: Configure CMake
      run: |
          cmake -S . -B ./build -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE -DENABLE_COVERAGE:BOOL=${{ matrix.ENABLE_COVERAGE }}

    - name: Build
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build ./build --config $BUILD_TYPE

    - name: Linux - Test and coverage
      if: runner.os != 'Windows'
      working-directory: ./build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: |
          sudo apt-get install -y lcov
          
          # reset counters
          lcov --zerocounters --directory .

          # run tests to generate gcda/gcno files
          ctest -C $BUILD_TYPE
          
          # baseline coverage
          lcov -i -c -b ${{github.workspace}}/build -d . -o coverage.info.baseline

          # covered area
          lcov --capture -b ${{github.workspace}}/build -d . --output-file coverage.info --rc lcov_branch_coverage=1

          # clean up initial and covered info files
          lcov --remove coverage.info 'build/*' '**/test/*' '/usr/*' '**/gtest/*' '**/glm/*' --output-file coverage.info.cleaned 
          lcov --remove coverage.info.baseline 'build/*' '**/test/*' '/usr/*' '**/gtest/*' '**/glm/*' --output-file coverage.info.baseline.cleaned

          # combine info files
          lcov -a coverage.info.baseline.cleaned -a coverage.info.cleaned -o coverage.info.combined

    - name: Windows - Test and coverage
      if: runner.os == 'Windows'
      working-directory: ./build
      run: |
        OpenCppCoverage.exe --sources cpp_starter_project --export_type cobertura:coverage.xml --cover_children -- ctest -C $BUILD_TYPE

    - name: 'Upload Coverage Report'
      uses: zgosalvez/github-actions-report-lcov@v1.4.0
      with:
        coverage-files: ./build/coverage.xml
        artifact-name: code-coverage-report-${{ runner.os }}
        github-token: ${{ secrets.GITHUB_TOKEN }}